[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { workspace = true, features = ["playground"] }
async-graphql-axum = "5.0"
axum = { version = "0.6", default-features = false, features = ["http1", "http2", "tokio"] }
clap = { workspace = true }
color-eyre = { workspace = true }
common = { workspace = true }
database = { workspace = true }
eyre = { workspace = true }
graphql = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tower = { version = "0.4", default-features = false }
tower-http = { version = "0.4", default-features = false, features = ["request-id", "trace"] }
tracing = { workspace = true }
uuid = { version = "1", features = ["v4"] }

[workspace]
members = [
  "common",
  "database",
  "graphql",
  "migrator",
  "xtask",
]

[workspace.dependencies]
async-graphql = { version = "5.0", features = ["chrono"], default-features = false }
clap = { version = "4.3", features = ["derive", "env"] }
chrono = "0.4"
color-eyre = "0.6"
eyre = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", default-features = false, features = ["chrono", "json", "migrate", "macros", "postgres", "runtime-tokio", "tls-rustls"] }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["log"] }

common = { path = "./common" }
database = { path = "./database" }
graphql = { path = "./graphql" }
migrator = { path = "./migrator" }
