[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
  "common",
  "migrator",
  "xtask",
]

[workspace.dependencies]
clap = { version = "4.3", features = ["derive", "env"] }
color-eyre = "0.6"
eyre = "0.6"
sqlx = { version = "0.7", default-features = false, features = ["migrate", "macros", "postgres", "runtime-tokio", "tls-rustls"] }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["log"] }

common = { path = "./common" }
migrator = { path = "./migrator" }
