[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { workspace = true, features = ["playground"] }
async-graphql-axum = "5.0"
axum = { workspace = true, features = ["http1", "http2", "query", "tokio"] }
axum-extra = { version = "0.7", features = ["cookie"] }
base64 = "0.21"
blake3 = "1"
bytes = "1"
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true }
color-eyre = { workspace = true }
common = { workspace = true }
cookie = "0.17"
database = { workspace = true }
eyre = { workspace = true }
form_urlencoded = "1.2"
futures = { workspace = true }
graphql = { workspace = true }
hmac = "0.12"
rand = { workspace = true }
redis = { version = "0.23", default-features = false, features = ["aio", "connection-manager", "tokio-comp"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10"
tokio = { workspace = true, features = ["signal", "sync"] }
tower = { workspace = true }
tower-http = { version = "0.4", default-features = false, features = ["request-id", "trace"] }
tracing = { workspace = true }
url = "2.4"
uuid = { version = "1", features = ["v4"] }

[workspace]
members = [
  "common",
  "database",
  "graphql",
  "migrator",
  "xtask",
]

[workspace.dependencies]
async-graphql = { version = "5.0", features = ["chrono"], default-features = false }
axum = { version = "0.6", default-features = false }
clap = { version = "4.3", features = ["derive", "env"] }
chrono = "0.4"
color-eyre = "0.6"
eyre = "0.6"
futures = { version = "0.3", default-features = false, features = ["async-await", "std"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", default-features = false, features = ["chrono", "json", "migrate", "macros", "postgres", "runtime-tokio", "tls-rustls"] }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
tower = { version = "0.4", default-features = false }
tracing = { version = "0.1", features = ["log"] }

common = { path = "./common" }
database = { path = "./database" }
graphql = { path = "./graphql" }
migrator = { path = "./migrator" }
