version: '3'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: super-secure-password
    networks:
      - default
    ports:
      - "4232:5432"

networks:
  default:
